services:
  generatedata:
    image: ghcr.io/mvisonneau/generatedata:latest
    environment:
      GD_DB_HOSTNAME: mysql
      GD_DB_NAME: generatedata
      GD_DB_USERNAME: root
    ports:
      - 8000:8080
    links:
      - mysql

  mysql:
    image: docker.io/library/mariadb:10.4
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: generatedata