version: '3.7'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    image: lewinc/rabbitmq
    hostname: rabbitmq.local
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
