# version: '3'
services:
  plantuml:
    container_name: plantuml
    ## Set via direnv
    image: plantuml/plantuml-server:${PLANTUML_VERSION}
    ports:
      - "58080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx2024m -XX:+ExitOnOutOfMemoryError
    networks:
      - plantuml

networks:
  plantuml:
