# version: '3'
services:
  plantuml:
    container_name: plantuml
    image: plantuml/plantuml-server:v1.2026.2
    ports:
      - "58080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx2024m -XX:+ExitOnOutOfMemoryError
    networks:
      - plantuml

networks:
  plantuml:
